<?php

namespace AppBundle\Repository;

/**
 * TravelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelsRepository extends \Doctrine\ORM\EntityRepository
{
}
